Record
udberg/Active-Record pull request #2
Opened 2021-01-30 09:37 UTC by Murodjon000

### Hi Tse 🙌
This active record has 3 modals.

- User 
- Post
- Comment

2021-01-31 11:40 UTC, LamiaSristy requested changes
# Status: Change Required. ♻️

Hello @ 🙌

Great work so far.

You need to implement the works below to get the project approved!🛠️

Please check my points here: 👇

`[REQUIRED]`
 - [x] README.md file need to have a small description of the project, like what the is a project about.
 - [x] In istalling part in README.md, `after Unpack (if downloaded);` add commands, 
        `bundle install` to get the necesary gems.
        `yarn` .
        `rails db:migrate`.
 - [x] Your PR message also needs to be descriptive.
 - [x] Please keep your commit messages in the imperative/present tense and add a description of the commit with it.
 - [ ] In your `Post.rb` you need to validate the title.


Please make the changes and ask for a re-review.

Feel free to reach me at @lamiasristy 🙋

2021-01-31 11:41 UTC, LamiaSristy commented on app/models/post.rb
> +  validates :user_id, presence: true
validations are present (`body` and `title` in automated tests but can be anything else) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/postValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

2021-02-01 10:23 UTC, rindrajosia requested changes
**Changes required**
Hello Team!!
You did a very good job.
However to move forward you have to make some changes:
REQUIRED:
- [x]  `username` should be present in your `user model` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] Make sure that information in your Readme file correspond with your code:
In your `Readme file`, you are telling that you have `Author model` however, when I check your code, you have `user model`
![1](https://user-images.githubusercontent.com/58552748/106445451-19737f80-6490-11eb-93ed-dbdb7e386f52.png)

- [ ] File '.stylelintrc.json' is missing
![2](https://user-images.githubusercontent.com/58552748/106445660-5ccdee00-6490-11eb-9f0f-361e688a59a3.png)

Please, make the suggested changes and submit a new code review request
Thanks
Rindra Josia

2021-02-01 10:37 UTC, mimipeshy commented
#### STATUS : CHANGES REQUESTED :red_circle: :recycle: 

Hey team @Murodjon000 and @udberg :wave: good job on working on the TSE comments. However, some changes are yet to be implemented before marking the project as complete

- [ ] **username** should be present in your user model([screenshot)](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png) . 

- [ ]  Make sure that information in your Readme file corresponds with your code:

In your Readme file, you are telling me that you have an **Author** model however when I check your code, you have a **user** model
![image](https://user-images.githubusercontent.com/33067256/106447251-4fb1fe80-6492-11eb-81ea-38b4d8505e4f.png)

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

2021-02-01 11:47 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2021-02-01 11:47 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2021-02-01 13:01 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @udberg and @Murodjon000  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] username should be present in your user model([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png)).

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-01 13:01 UTC, descholar-ceo commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
In this user model, you should validate if `username` exists

2021-02-01 14:36 UTC, Murodjon000 commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
Bro i validated name and you are saying username what is sense.Name and username is similar only thing username have more words than name.If I am wrong sorry bro.You are only saying typo mistakes I dont understand what is sense.

2021-02-01 15:06 UTC, mimipeshy commented
#### STATUS : APPROVED :partying_face: 

Hey team @Murodjon000 and @udberg :wave: good job on working on the feedback given by the TSE's. This project is therefore approved go ahead and merge.

All the best in the next projects. Happy Coding :computer: 

Regards
Peris Ndanu

2021-02-01 15:11 UTC, merged